// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
#[allow(unused_imports)] // Not using METHOD_ID
use methods::{METHOD_ELF, METHOD_ID};

use issuer_core::{CountNullifiersInput, CountNullifiersJournal};
use risc0_zkp::core::digest::Digest;
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Structure the input.
    let input = CountNullifiersInput {
        document_hash: vec![],
        blinder: vec![],
        salts: vec![],
        merkle_root: Digest::default(),
        merkle_proofs: vec![],
    };

    // Initialize the environment and write an input.
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, METHOD_ELF).unwrap();

    let receipt = prove_info.receipt;
    let output: CountNullifiersJournal = receipt.journal.decode().unwrap();

    println!("Journal: {output}");
}
